---
- name: Get the OpenShift Business Partner Supported NFR pool-ID
  shell: "subscription-manager list --available | awk -F : \
         'BEGIN {s=0}
          /Subscription Name: *OpenShift Business Partner Supported NFR/ {s=1}
          s==1 && /Pool ID:/ {print $2; s=2}'"
  register: openshift_NFR_pool_id
  changed_when: False

- name: Enable OpenShift Business Partner Supported NFR repos
  command: "subscription-manager attach --pool={{ openshift_NFR_pool_id.stdout }}"
  when: openshift_NFR_pool_id.stdout != ''

- name: Enable RHEL repositories
  command: subscription-manager repos \
               --enable="rhel-7-server-rpms" \
               --enable="rhel-7-server-extras-rpms" \
               --enable="rhel-7-server-optional-rpms" \
               --enable="rhel-7-server-ose-3.0-rpms"



